# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f8aae0a4ccdbf39c5f4cad32c05bda085b3201ffb5ba5eea23bfeec3be41a72507c5ec9e363f8e70e9953fb734c9209c79c774549a86e7a8f515240639c6608

test:
  secret_key_base: 874c37fb910a57f341d2261fbbac4b41ef37be4f57fd77efdeb77c3a0f4a7d776dcb52c0fb794b6f4561d32c154ae301bfd954b0bc29110e9deb89877329218e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
